### PR TITLE
Bump to Rails 5.2.3

### PR DESCRIPTION
**Pull request by larouxn**
Quick update, Rails [`5.2.2.1`](https://weblog.rubyonrails.org/2019/3/15/this-week-in-rails-security-fixes-bulk-insert-and-upsert-seeds-replanting/) -> [`5.2.3`](https://weblog.rubyonrails.org/2019/3/28/Rails-5-2-3-has-been-released/)

Follow up to https://github.com/railsgirls-jp/railsgirls-jp.github.io/pull/441.

### CODE REVIEW

**Comment by larouxn** [comment]
For review, @eitoball.

**Review by eitoball — APPROVED** [review]
LGTM

**Comment by eitoball** [comment]
@larouxn Could you resolve conflict?

**Comment by larouxn** [comment]
Should be ready now. ⛵️

**Comment by eitoball** [comment]
Thank you.

**Pull request merged**
